# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: createReadme
        name: createReadme
        entry: python createReadme.py
        language: python

    default_language_version:
    python: python3.10
